<h2>Edition de tournoi</h2>
<form action="/res03-projet-final/purge_tournament/admin/tournaments/edit" method="post" id="tournament-form">
    <section class="top32-info" id="tournament-info">
    <fieldset>
        <label for="tournamentName">Name</label>
        <input type="text" name="tournamentName" value="<?= $data['tournament']['name']?>"/>
    </fieldset>
    <fieldset>
        <label for="tournamentDate">Starting Time</label>
        <input type="datetime-local" name="tournamentDate" value="<?= $data['tournament']['date']?>"/>
    </fieldset>
    <fieldset>
        <label for="gameName">Game</label>
        <input type="text" name="gameName" value="<?= $data['tournament']['gameName']?>"/>
    </fieldset>
    <fieldset>
        <label for="tournamentDescription">Description</label>
        <textarea name="tournamentDescription" value="<?= $data['tournament']['description']?>"></textarea>
    </fieldset>
    <fieldset>
        <label for="streamURL">Stream URL</label>
        <input type="url" name="streamURL" value="<?= $data['tournament']['streamURL']?>"/>
    </fieldset>
    </section>
    <section class="top32" id="first-bracket">
        <h3>16 ème de finale</h3>
        <?php
            for ($i = 0; $i <= 15; $i++) { ?>
                <fieldset>
                <button></button>
                </fieldset>
            <?php } ?>
        ?>
    <section class="top32" id="second-bracket">
    </section>
    <section class="top16" id="third-bracket">

    </section>
    <section class="top16" id="fourth-bracket">

    </section>
    <section class="top8" id="fifth-bracket">

    </section>
    <section class="top8" id="sixth-bracket">

    </section>
    <section class="top4" id="seventh-bracket">

    </section>
    <section class="top4" id="eighth-bracket">

    </section>
    <section class="top2" id="ninth-bracket">

    </section>
    <input type="submit" value="edit" name="edit" id="tournament-edit-btn"/>
    <input type="hidden" name="formName" value="tournament-edit"/>
    <button id="reset-edit">Reset</button>
</form>

<?php echo '<pre>',print_r($data['tournament']),'</pre>'; ?>
