<!DOCTYPE html>
<html lang="fr">
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Purge Tournament</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/res03-projet-final/purge_tournament/assets/styles/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>
    <body>
        <?php
            require 'partials/_header.phtml'; // Je charge le header dans le dossier partials.
        ?>
        <main>

        <?php
              require  $template.".phtml"; // Je charge la page dont j'ai besoin avec la variable donnée par mon render.
        ?>
        </main>

        <?php
            require 'partials/_footer.phtml'; // Je charge le footer dans le dossier partials.
        ?>
    </body>
</html>