<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta name="title" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="referrer" content="">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <meta property="og:image" content="">
    <meta charset="utf-8">
    <title>Purge Tournament</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style/css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
<?php
    require 'partials/_header.phtml'; // Je charge le header dans le dossier partials.
?>
<main>

<?php
      require  $template."/".$template.".phtml"; // Je charge la page dont j'ai besoin avec la variable donnée par mon render.
?>
</main>

<?php
    require 'partials/_footer.phtml'; // Je charge le footer dans le dossier partials.
?>

</body>
</html>