<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="title" content="Purge Tournament">
        <meta name="description" content="La meilleure plateforme de tournois mobile">
        <meta name="author" content="Valmonzo">
        <meta name="referrer" content="Valmonzo">
        <meta name="image" content="http://valmontpehautpietri.sites.3wa.io/res03-projet-final/purge_tournament/assets/img/purgelogo.png">
        <meta property="og:title" content="Purge Tournament">
        <meta property="og:description" content="La meilleure plateforme de tournois mobile">
        <meta property="og:locale" content="fr_FR">
        <meta property="og:image" content="http://valmontpehautpietri.sites.3wa.io/res03-projet-final/purge_tournament/assets/img/purgelogo.png">
        <meta charset="utf-8">
        <title>Purge Tournament</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/res03-projet-final/purge_tournament/assets/styles/css/style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer">
    </head>
    <body>
        <h1 class="sr-only">Purge Tournament : Entreprise d'organisation de tournoi</h1>
        <?php
            require 'partials/_header.phtml';
        ?>
        <main>
        <?php
              require  $template.".phtml";
        ?>
        </main>
        <?php
            require 'partials/_footer.phtml';
        ?>
    </body>
</html>