<footer class="main-footer">
  <div class="footer-content">
    <p>&copy; <?= date('Y'); ?> Valmonzo. All Rights Reserved. </p>
    <ul class="social-links">
      <li>
        <a href="#">
          <span class="fa fa-twitter"></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-facebook"></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-instagram"></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-twitch"></span>
        </a>
      </li>
    </ul>
  </div>
</footer>