<header id="admin-header">
  <nav>
    <ul>
      <li id="username-header">
        <a href="/res03-projet-final/purge_tournament/admin">Bienvenue <span> <?= $_SESSION['username'];?> </span>! </a>
      </li>
      <li>
        <a href="/res03-projet-final/purge_tournament/logout">Se déconnecter</a>
      </li>
      <li>
        <a href="/res03-projet-final/purge_tournament/admin/teams">Teams</a>
      </li>
      <li>
        <a href="/res03-projet-final/purge_tournament/admin/tournaments">Tournaments</a>
      </li>
    </ul>
  </nav>
</header>