<form action="/res03-projet-final/purge_tournament/admin/teams/create" method="post" class="form-team">
  <h2>Créer une team</h2>
  <fieldset>
    <label for="teamName">Nom</label>
    <input type="text" name="teamName" />
  </fieldset>
  <fieldset>
    <label for="teamP1">Joueur 1</label>
    <input type="text" name="teamP1" />
  </fieldset>
  <fieldset>
    <label for="teamP2">Joueur 2</label>
    <input type="text" name="teamP2" />
  </fieldset>
  <fieldset>
    <label for="teamP3">Joueur 3</label>
    <input type="text" name="teamP3" />
  </fieldset>
  <fieldset>
    <label for="teamP4">Joueur 4</label>
    <input type="text" name="teamP4" />
  </fieldset>
  <fieldset>
    <label for="teamPSub">Remplaçant</label>
    <input type="text" name="teamPSub" />
  </fieldset>
  <fieldset>
    <label for="coach">Coach</label>
    <input type="text" name="coach" />
  </fieldset>
  <fieldset>
    <label for="logo">Logo</label>
    <input type="url" name="logo" />
  </fieldset>
  <fieldset>
    <input type="submit" name="send" value="Créer" id="team-create-btn" />
  </fieldset>
  <input type="hidden" name="formName" value="team-create" />
</form>