<h2>Editer une team</h2>
<form action="/res03-projet-final/purge_tournament/admin/teams/<?= $data['team']->getId(); ?>/edit" method="post">
    <fieldset>
    <label for="teamName">Team Name</label>
    <input type="text" name="teamName" value="<?= $data["team"]->getName(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="teamP1">Player One</label>
    <input type="text" name="teamP1" value="<?= $data["team"]->getPlayerOne(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="teamP2">Player Two</label>
    <input type="text" name="teamP2" value="<?= $data["team"]->getPlayerTwo(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="teamP3">Player Three</label>
    <input type="text" name="teamP3" value="<?= $data["team"]->getPlayerThree(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="teamP4">Player Four</label>
    <input type="text" name="teamP4" value="<?= $data["team"]->getPlayerFour(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="teamPSub">Sub Player</label>
    <input type="text" name="teamPSub" value="<?= $data["team"]->getSubPlayer(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="coach">Coach Name</label>
    <input type="text" name="coach" value="<?= $data["team"]->getCoach(); ?>"/>
    </fieldset>
    <fieldset>
    <label for="logo">URL of your logo</label>
    <input type="url" name="logo" value="<?= $data["team"]->getLogo(); ?>"/>
    </fieldset>
    <fieldset>
            <input type="submit" name="send" value="Edit" id="team-edit-btn" />
        </fieldset>
        <input type="hidden" name="formName" value="team-edit"/>
</form>