<footer class="main-footer">
  <section class="footer-content">
    <h2 class="sr-only">Copyright & social link</h2>
    <p>&copy; <?= date('Y'); ?> Valmonzo. Tous droits réservés. </p>
    <ul class="social-links">
      <li>
        <a href="#">
          <i class="fa-brands fa-twitter"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa-brands fa-facebook"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa-brands fa-instagram"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa-brands fa-twitch"></i>
        </a>
      </li>
    </ul>
  </section>
</footer>