<footer class="main-footer">
  <div class="footer-content">
    <p>&copy; <?= date('Y'); ?> Valmonzo. Tous droits réservés.</p>
    <ul class="social-links">
      <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
      <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
      <li><a href="#"><i class="fa-brands fa-twitch"></i></a></li>
    </ul>
  </div>
</footer>