<h2 class=sr-only>A propos de la Purge</h2>
<div class="about-us-container">
  <section class="about-us">
    <h3>L'équipe</h3>
    <article>
      <h4 class="card-name">PurgeKing</h4>
      <figure>
        <img src="assets/img/adrien.png" alt="photo de adrien">
      </figure>
      <ul class="card-list">
        <li>
          <span>Nom : </span> Favaud
        </li>
        <li>
          <span>Prénom :</span> Adrien
        </li>
        <li>
          <span>Poste :</span> Fondateur
        </li>
        <li>
          <span>Présentation :</span> Avec plus de 10 ans d'expérience dans les tournois e-sport , Adrien décide de monter sa propre entreprise pour correspondre à ses valeurs humaines. Il est aujourd'hui le décisionnaire de Purge Tournament.
        </li>
      </ul>
    </article>
    <article>
      <h4 class="card-name">Bribri</h4>
      <figure>
        <img src="assets/img/brigitte.jpeg" alt="photo de brigitte">
      </figure>
      <ul class="card-list">
        <li>
          <span>Nom :</span> Durand
        </li>
        <li>
          <span>Prénom :</span> Brigitte
        </li>
        <li>
          <span>Poste :</span> Directrice Executive
        </li>
        <li>
          <span>Présentation :</span> Réel bras droit de notre Fondateur, elle est l'essence même de l'évolution saine au sein d'une entreprise. En effet, arrivée à la création de Purge Tournament, elle a contribué grandement à la mise en place d'un environnement stable.
        </li>
      </ul>
    </article>
    <article>
      <h4 class="card-name">Jeannou</h4>
      <figure>
        <img src="assets/img/jean.jpeg" alt="photo de jean">
      </figure>
      <ul class="card-list">
        <li>
          <span>Nom : </span> Branude
        </li>
        <li>
          <span>Prénom : </span> Jean
        </li>
        <li>
          <span>Poste : </span> Community Manager
        </li>
        <li>
          <span>Présentation :</span> Humour, délicatesse et talent sont les mots qui définissent Jean. Il tient les nos réseaux d'une main de maître, l'un des meilleurs dans son domaine.
        </li>
      </ul>
    </article>
    <article>
      <h4 class="card-name">Valmonzo</h4>
      <figure>
        <img src="assets/img/valmont.jpeg" alt="photo de valmont">
      </figure>
      <ul class="card-list">
        <li>
          <span>Nom :</span> Pehaut-Pietri
        </li>
        <li>
          <span>Prénom :</span> Valmont
        </li>
        <li>
          <span>Poste :</span> Developpeur Web
        </li>
        <li>
          <span>Présentation :</span> Arrivé à la création de l'entreprise, il est à l'origine même de la structure de cette entreprise, il travaille sans cesse pour permettre à notre plateforme d'évoluer.
        </li>
      </ul>
    </article>
  </section>
  <section class="section-friends">
    <h3>Nos sponsors</h3>
    <p>Ils nous accompagnent dans nos projets au quotidiens et nous permettent d'évoluer sans cesse:</p>
    <ul class="friends-list">
      <li>
        <a href="https://www.riotgames.com/fr">
          <figure>
            <img src="assets/img/riot.jpeg" alt="logo riot">
          </figure>
        </a>
      </li>
      <li>
        <a href="https://www.bluestacks.com/fr/index.html">
          <figure>
            <img src="assets/img/bluestack.png" alt="logo bluestack">
          </figure>
        </a>
      </li>
      <li>
        <a href="https://www.guilded.gg/">
          <figure>
            <img src="assets/img/guilded.png" alt="logo guilded">
          </figure>
        </a>
      </li>
      <li>
        <a href="https://omlet.gg/">
          <figure>
            <img src="assets/img/omlet.png" alt="logo omlet">
          </figure>
        </a>
      </li>
      <li>
        <a href="https://trovo.live/">
          <figure>
            <img src="assets/img/trovo.jpeg" alt="logo trovo">
          </figure>
        </a>
      </li>
    </ul>
  </section>
</div>