<section id="contact-form">
    <h1 class="sr-only">Formulaire de contact</h1>
    <form action="/res03-projet-final/purge_tournament/contact" method="post">
        <h2>Contactez nous !</h2>
        <fieldset>
            <label for="contactName">Nom & prénom</label>
            <input type="text" name="contactName"  placeholder="Votre nom & prénom" />
        </fieldset>
        <fieldset>
            <label for="contactEmail">Email</label>
            <input type="email" name="contactEmail"  placeholder="Votre email" />
        </fieldset>
        <fieldset>
            <label for="contactMessage">Message</label>
            <textarea name="contactMessage"rows="5" cols="33" placeholder="Votre message ..."></textarea>
        </fieldset>
        <fieldset>
            <input type="submit" name="Envoyer" value="Envoyer" id="contact-btn" />
        </fieldset>
        <input type="hidden" name="formName" value="contact"/>
    </form>
</section>