<section id="login">
    <form action="/res03-projet-final/purge_tournament/admin" method="post">
        <h3>Connexion</h3>
        <fieldset>
            <label for="email">Email</label>
            <input type="email" name="email"  placeholder="Email administrateur" />
        </fieldset>
        <fieldset>
            <label for="password">Mot de passe</label>
            <input type="password" name="password"  placeholder="Mot de passe" />
        </fieldset>
        <fieldset>
            <input type="submit" name="submit" value="Se connecter" id="login-button" />
        </fieldset>
        <input type="hidden" name="formName" value="login"/>
    </form>
</section>