<h2 class="sr-only">Homepage</h2>
<section id="homepage-header">
    <h3>Bienvenue sur la Purge Tournament</h3>
    <p>Une plateforme de tournoi pour tous les jeux mobiles</p>
</section>
<section id="homepage-main">
    <h3>Rejoignez nous !</h3>
    <p>Que vous soyez une team ou une entreprise, nous pouvons répondre à vos attentes</p>
    <button onclick="#"><i class="fa-brands fa-discord"></i>Notre discord</button>
</section>
