<h2 class="sr-only">Homepage</h2>
<section id="homepage-header">
    <figure id="move-logo">
        <img src="assets/img/purgelogo.png" alt="Logo représentant un nuage atomique avec le nom de l'entreprise">
    </figure>
    <h3>Bienvenue chez The Purge Tournament</h3>
    <p>Une plateforme de tournoi pour tous les jeux mobiles</p>
    <h4>Notre devise :</h4>
    <q cite="https://purgetournament.com/">"Dans cette communauté internationale, vous êtes sûres de trouver la bonne compétition pour le jeu que vous désirez"</q>
</section>
<section id="homepage-main">
    <h3>Rejoignez nous !</h3>
    <p>Que vous soyez une team ou une entreprise, nous pouvons répondre à vos attentes</p>
    <button onclick="#" id="move-btn"><span class="fa-brands fa-discord"></span>Notre discord</button>
</section>
<script type="module" src="/res03-projet-final/purge_tournament/assets/js/homepage.js"></script>
