<h2 id="live-title">The Purge Tournament Live <span class="fa-solid fa-circle"></span></h2>
<section class="twitch-container">
    <h3 class=sr-only>twitch container</h3>
    <section class="twitch">
      <h3 class="sr-only">Lecteur vidéo twitch</h3>
      <div class="twitch-video">
        <iframe
          src="https://player.twitch.tv/?channel=purgetournament&parent=valmontpehautpietri.sites.3wa.io"
          height="378"
          width="620">
        </iframe>
      </div>
      <div class="twitch-chat">
        <iframe
          src="https://www.twitch.tv/embed/purgetournament/chat?parent=valmontpehautpietri.sites.3wa.io"
          height="500"
          width="350">
        </iframe>
      </div>
    </section>
</section>


